project_id = "elnybcgxfjzabmrmhcrr"

[functions.pytrends-ingest]
verify_jwt = false

[functions.send-itinerary-email]
verify_jwt = false

[functions.send-quiz-email]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.blog-cron-trigger]
verify_jwt = false

[functions.weekly-selector]
verify_jwt = false

[functions.seasonal-selector]
verify_jwt = false

[functions.reset-selector-state]
verify_jwt = false

[functions.scrape-reviews]
verify_jwt = false

[functions.daily-summary-email]
verify_jwt = false
